### ndarray Task

In [67]:
import numpy as np

#1 1~10까지의 요소를 ndarray에 담는다.
# ndarray1 = np.array([i for i in range(1, 11)])
ndarray1 = np.array(list(range(1, 11)))
print(type(ndarray1), ndarray1.shape, ndarray1.ndim, ndarray1.dtype, sep="\n")

print("=" * 50)

#2 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1을 담는다.
python_list = []
python_list.append([6 - i for i in range(2)])
python_list.append([4 - i for i in range(2)])
python_list.append([2 - i for i in range(2)])

ndarray2 = np.array(python_list)
print(type(ndarray2), ndarray2.shape, ndarray2.ndim, ndarray2.dtype, sep="\n")

print("=" * 50)

#3 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다(transpose, 전치).
ndarray3 = np.array([[(5 - i) * 2 for i in range(4)]]).T
print(type(ndarray3), ndarray3.shape, ndarray3.ndim, ndarray3.dtype, sep="\n")

print("=" * 50)

# #1에서 제작된 ndarray의 요소 타입 출력
print(ndarray1.dtype)

print("=" * 50)

# #1에서 제작된 ndarray의 차원 출력
print(ndarray1.shape)

print("=" * 50)

# #2에서 제작된 ndarray의 요소 타입을 float으로 변환
ndarray2_float32 = ndarray2.astype(np.float32)
print(ndarray2_float32)

print("=" * 50)

# #2에서 제작된 ndarray의 차원 출력
print(ndarray2.shape)

print("=" * 50)

# #3에서 제작된 ndarray의 요소 타입을 int8로 변환
ndarray2_int8 = ndarray2.astype(np.int8)
print(ndarray2_int8.dtype, ndarray2_int8, sep="\n")

print("=" * 50)

# #3에서 제작된 ndarray의 요소에 5씩 더하기
ndarray3_result = ndarray3 + 5
print(ndarray3_result)

print("=" * 50)

# #3에서 제작된 ndarray의 차원 출력
print(ndarray3.shape)

<class 'numpy.ndarray'>
(3, 3)
2
int32


TypeError: 'list' object is not callable

### arange, zeros, ones Task

In [29]:
import numpy as np

# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32 인 ndarray 만들기
ndarray = np.zeros((10, ), dtype=np.int32)
print(ndarray, ndarray.dtype, ndarray.shape)

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray = np.ones((3, 4), dtype=np.int8)
print(ndarray, ndarray.dtype, ndarray.shape)

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray = np.arange(5)
print(ndarray, ndarray.dtype, ndarray.shape)

[0 0 0 0 0 0 0 0 0 0] int32 (10,)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int8 (3, 4)
[0 1 2 3 4] int32 (5,)


### reshape Task

In [41]:
import numpy as np

ndarray1 = np.arange(start=0, stop=16)
ndarray1

print("=" * 50)

# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2.shape, ndarray2, sep="\n")

print("=" * 50)

# 2 Dimension, axis 0은 8로 변경
ndarray3 = ndarray1.reshape((8, -1))
print(ndarray3.shape, ndarray3, sep="\n")

print("=" * 50)

# 3 Dimension으로 변경
ndarray4 = ndarray1.reshape((4, 2, -1))
print(ndarray4.shape, ndarray4, sep="\n")

print("=" * 50)

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray5 = ndarray4.reshape((-1, 1))
print(ndarray5.shape, ndarray5, sep="\n")

print("=" * 50)

# ndarray3을 1 Dimension으로 변환
ndarray6 = ndarray4.reshape((-1,))
print(ndarray6.shape, ndarray6, sep="\n")

(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(4, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
(16, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
(16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Indexing Task

In [19]:
import numpy as np

# 1. 위치 인덱싱(Location indexing)
# 1-1. 1차원 배열 1~100값 중 97값 추출하기
ndarray1 = np.arange(1, 101)
print(ndarray1[-4])

print("=" * 50)

# 1-2. 1~30까지의 요소를 ndarray에 담는다.
ndarray1 = np.arange(start=1, stop=31)
print(ndarray1)

print('=' * 50)

# 2. 2차원 위치 인덱싱(Location indexing)
# 2-1. 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 중 15값 추출하기
ndarray1 = np.arange(1, 21)
ndarray2 = ndarray1.reshape((4,5))
print(ndarray2[2, 4])

print("=" * 50)

# 2-2. Dimension, axis 0은 5로 변경
ndarray2 = ndarray1.reshape((5, -1))
print(ndarray2)

print("=" * 50)

# 2-3. 2행의 4번째 숫자 출력 (Location indexing)
print(ndarray2[1,3])

print("=" * 50)

# 3. 불린 인덱싱 (Boolean indexing)
# 3-1. 1~100중 짝수만 출력
ndarray1 = np.arange(1, 101)
ndarray2 = ndarray1[ndarray1 % 2 == 0]
print(ndarray2)

print("=" * 50)

# 3-2. 3-1에서 구한 요소를 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출하기
ndarray2 = ndarray1.reshape((10, -1))
ndarray3 = ndarray2[8:]
print(ndarray3.flatten())

print("=" * 50)

# 3-3. 3-2에서 구한 요소 중 x:86 y:100 좌표 구하기
ndarray4 = ndarray3[[0, 1],[2, 4]] 
print(ndarray4)

print("=" * 50)

# 3-4. 불리언 인덱싱을 사용하여 각 요소중 1의 자리가 2인 수들만 추출하시오
ndarray1 = np.arange(1, 101)
ndarray2 = ndarray1[ndarray1 % 2 == 0]
cond = ndarray2 % 10 == 2
ndarray3 = ndarray2[cond]

print(ndarray3)

print("=" * 50)

# 3-5. 1~49 요소 중 2와 5의 공배수를 추출하세요.
ndarray1 = np.arange(start=1, stop=50)

cond1 = ndarray % 2 == 0
cond2 = ndarray % 5 == 0
cond3 = cond1 & cond2

ndarray2 = ndarray[cond3]
print(ndarray2)

print("=" * 50)

# 3-6. 3-5에서 추출한 공배수 중 20이상인 값만 추출하세요.
print(ndarray2[(ndarray2 >= 20)])

97
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
15
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
8
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100]
[83 95]
[ 2 12 22 32 42 52 62 72 82 92]
[10 20 30 40]
[20 30 40]


### np.argsort() Task

In [33]:
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# ndarray.ravel(): 2차원 넘파이 배열을 1차원 넘파이 배열로 변경(mutable)
# ndarray.flatten(): 2차원 넘파이 배열을 1차원 넘파이 배열로 변경(immutable)

# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]

In [25]:
# [[과일이름], [가격]], 가격별 내림차순
ndarray = np.array(array1)
print(ndarray)
fruit_name = ndarray[:1].flatten()
fruit_price = ndarray[1:2].flatten()
print(fruit_name, fruit_price)

fruit_name_sorted_desc = fruit_name[np.argsort(fruit_price)[::-1]]
print(fruit_name_sorted_desc)

[['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
 ['1500' '1800' '2000' '2500' '8500']]
['Mango' 'Apple' 'Pear' 'Pitch' 'Melon'] ['1500' '1800' '2000' '2500' '8500']
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']


In [29]:
# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
ndarray = np.array(array2)
print(ndarray)

# 나이별 내림차순
names = ndarray[:1].flatten()
ages = ndarray[1:2].flatten().astype(np.int32)
print(names, ages)

names_sorted_by_ages_desc = names[np.argsort(ages)[::-1]]
print(names_sorted_by_ages_desc)

# 학점별 오름차순
grades = ndarray[2:3].flatten()
names_sorted_by_grades = names[np.argsort(grades)]
print(names_sorted_by_grades)

[['둘리' '또치' '길동' '도너' '마이콜']
 ['7' '9' '40' '5' '20']
 ['C' 'A' 'B' 'F' 'D']]
['둘리' '또치' '길동' '도너' '마이콜'] [ 7  9 40  5 20]
['길동' '마이콜' '또치' '둘리' '도너']
['또치' '길동' '둘리' '마이콜' '도너']


In [34]:
# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
ndarray = np.array(array3)
print(ndarray)

nations = ndarray[:1].flatten()
increase_ratings_of_GDP = []

increase_ratings_of_GDP_data = ndarray[1:2].flatten()

for i in increase_ratings_of_GDP_data:
    increase_ratings_of_GDP.append(i.replace('%', ''))

increase_ratings_of_GDP = np.array(increase_ratings_of_GDP, dtype=np.float32)
print(nations, increase_ratings_of_GDP)

nations_sorted_by_GDP = nations[np.argsort(increase_ratings_of_GDP)]
print(nations_sorted_by_GDP)

[['한국' '영국' '러시아' '남아프리카 공화국' '미국']
 ['1.7%' '-0.6%' '0.3%' '1.2%' '1.4%']]
['한국' '영국' '러시아' '남아프리카 공화국' '미국'] [ 1.7 -0.6  0.3  1.2  1.4]
['영국' '러시아' '남아프리카 공화국' '미국' '한국']


### Linear Equation Task

In [ ]:
# 다음 행렬을 내적하세요.

'''
A1      A2
1 2 3   7 8
4 5 6   9 10
        11 12
'''

In [36]:
# 다음 연립방정식을 전치 행렬과 행렬 내적 
# 그리고 역행렬(np.linalg.inv())을 통해 해결하세요.

# k = [[k1], [k2]]
# A = [[x1, x2], [y1, y2]]
# w = [[w1], [w2]]

# k1 = x1w1 + x2w2
# k2 = y1w1 + y2w2
# k = Aw

# x + 2y + 3z = 1
# x + 2y + z = 3
# x + 3z = 5

A = np.array([[1, 2, 3], [1, 2, 1], [1, 0, 3]])
k = np.array([[1, 3, 5]]).T
print(np.dot(np.linalg.inv(A), k))

[[ 8.]
 [-2.]
 [-1.]]


In [62]:
# 1x + 1y = 10
# 2x - 3y = 10

# Aw = k

A = np.array([[1,1],[2,-3]])
k = np.array([[10, 10]]).T

print(np.dot(np.linalg.inv(A), k))

TypeError: 'list' object is not callable